version: "3.7"

services:
  psql:
    container_name: "postgresql-container-requests"
    image: "postgres:11.3"
    ports:
      - "5432:5432"
    volumes:
      - "psql-data:/var/lib/postgresql/data"
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - cvt-pdf-analyzer-network
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB  

volumes:
  psql-data:

networks:
  cvt-pdf-analyzer-network:
