version: "3"

services:
  db:
    container_name: "postgresql-container-requests"
    image: "postgres:11.3"
    ports:
      - "5432:5432"
    volumes:
      - "psql-data:/var/lib/postgresql/data"
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - cvt-campaign-requests
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB  
  api:
    container_name: cvt-campaign-requests
    build: .
    volumes:
        - .:/app
    ports:
        - "8000:5000"
    depends_on:
        - db
    networks:
      - cvt-campaign-requests
    environment:
        - PGPASSWORD=campaign_requests
        - PGUSER=campaign_requests
        - DATABASE_URL=postgresql://db/campaign_requests
        - FLASK_APP=config.py

volumes:
  psql-data:

networks:
  cvt-campaign-requests:
