"""empty message

Revision ID: 75234bbee710
Revises: aecfaa52f69f
Create Date: 2019-06-27 14:38:28.943483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75234bbee710'
down_revision = 'aecfaa52f69f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_requests', sa.Column('campaign_end', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_requests', 'campaign_end')
    # ### end Alembic commands ###
