"""empty message

Revision ID: c7af7bf65861
Revises: 
Create Date: 2019-06-25 10:55:33.213295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7af7bf65861'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.String(), nullable=True),
    sa.Column('campaign_text', sa.String(), nullable=True),
    sa.Column('campaign_start', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_requests')
    # ### end Alembic commands ###
